sources:
  - name: airbnb
    display_name: Airbnb
    ats: greenhouse
    boards:
      - airbnb

  - name: anduril
    display_name: Anduril
    ats: greenhouse
    boards:
      - andurilindustries

  - name: aquatic_capital_management
    display_name: Aquatic Capital Management
    ats: greenhouse
    boards:
      - aquaticcapitalmanagement

  - name: cloudflare
    display_name: Cloudflare
    ats: greenhouse
    boards:
      - cloudflare

  - name: coinbase
    display_name: Coinbase
    ats: greenhouse
    boards:
      - coinbase

  - name: datadog
    display_name: Datadog
    ats: greenhouse
    boards:
      - datadog

  - name: disney
    display_name: Disney
    ats: greenhouse
    boards:
      - disney

  - name: flexport
    display_name: Flexport
    ats: greenhouse
    boards:
      - flexport

  - name: galaxy_digital
    display_name: Galaxy Digital
    ats: greenhouse
    boards:
      - galaxy

  - name: jane_street
    display_name: Jane Street
    ats: greenhouse
    boards:
      - janestreet

  - name: kalshi
    display_name: Kalshi
    ats: greenhouse
    boards:
      - kalshi

  - name: ramp
    display_name: Ramp
    ats: greenhouse
    boards:
      - rampnetwork

  - name: robinhood
    display_name: Robinhood
    ats: greenhouse
    boards:
      - robinhood

  - name: securitize
    display_name: Securitize
    ats: greenhouse
    boards:
      - securitize

  - name: stripe
    display_name: Stripe
    ats: greenhouse
    boards:
      - stripe

  - name: walleye_capital
    display_name: Walleye Capital
    ats: greenhouse
    boards:
      - walleyecapital-external-students

  - name: worldquant
    display_name: WorldQuant
    ats: greenhouse
    boards:
      - worldquant
