sources:
  - name: airbnb
    display_name: Airbnb
    ats: greenhouse
    boards:
      - airbnb

  - name: anduril
    display_name: Anduril
    ats: greenhouse
    boards:
      - andurilindustries

  - name: aquatic_capital_management
    display_name: Aquatic Capital Management
    ats: greenhouse
    boards:
      - aquaticcapitalmanagement

  - name: binance_us
    display_name: Binance.US
    ats: ashby
    boards:
      - binance.us

  - name: cloudflare
    display_name: Cloudflare
    ats: greenhouse
    boards:
      - cloudflare

  - name: coinbase
    display_name: Coinbase
    ats: greenhouse
    boards:
      - coinbase

  - name: datadog
    display_name: Datadog
    ats: greenhouse
    boards:
      - datadog

  - name: disney
    display_name: Disney
    ats: greenhouse
    boards:
      - disney

  - name: ellipsis_labs
    display_name: Ellipsis Labs
    ats: ashby
    boards:
      - ellipsislabs

  - name: flexport
    display_name: Flexport
    ats: greenhouse
    boards:
      - flexport

  - name: galaxy_digital
    display_name: Galaxy Digital
    ats: greenhouse
    boards:
      - galaxy

  - name: jane_street
    display_name: Jane Street
    ats: greenhouse
    boards:
      - janestreet

  - name: kalshi
    display_name: Kalshi
    ats: ashby
    boards:
      - kalshi

  - name: notion
    display_name: Notion
    ats: ashby
    boards:
      - notion

  - name: phantom
    display_name: Phantom
    ats: ashby
    boards:
      - phantom

  - name: plaid
    display_name: Plaid
    ats: ashby
    boards:
      - plaid

  - name: polymarket
    display_name: Polymarket
    ats: ashby
    boards:
      - polymarket

  - name: rain
    display_name: Rain
    ats: ashby
    boards:
      - rain

  - name: ramp
    display_name: Ramp
    ats: ashby
    boards:
      - ramp

  - name: replit
    display_name: Replit
    ats: ashby
    boards:
      - replit

  - name: robinhood
    display_name: Robinhood
    ats: greenhouse
    boards:
      - robinhood

  - name: securitize
    display_name: Securitize
    ats: greenhouse
    boards:
      - securitize

  - name: stripe
    display_name: Stripe
    ats: greenhouse
    boards:
      - stripe

  - name: walleye_capital
    display_name: Walleye Capital
    ats: greenhouse
    boards:
      - walleyecapital-external-students

  - name: worldquant
    display_name: WorldQuant
    ats: greenhouse
    boards:
      - worldquant
